/* 
 * Material didático destinado ao curso
 * de Programação Orientada a Objetos do 
 * Bacharelado em Ciência da Computação 
 * do IFNMG - Câmpus Montes Claros
 */
package io.github.guisso.poo.singletonframe;

import java.beans.PropertyVetoException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Luis Guisso <luis dot guisso at ifnmg dot edu dot br>
 * @version 0.0.1, 16/08/2021
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPrincipal = new javax.swing.JDesktopPane();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadastroA = new javax.swing.JMenuItem();
        mnuCadastroB = new javax.swing.JMenuItem();
        mnuCadastroC = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        mnuCadastro.setText("Cadastro");

        mnuCadastroA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadastroA.setText("Cadastro A");
        mnuCadastroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroAActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroA);

        mnuCadastroB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadastroB.setText("Cadastro B");
        mnuCadastroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroBActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroB);

        mnuCadastroC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadastroC.setText("Cadastro C");
        mnuCadastroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroCActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroC);

        mnuPrincipal.add(mnuCadastro);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroAActionPerformed
        InternaA internaA = new InternaA();
        dskPrincipal.add(internaA);
        tornarVisivel(internaA);
    }//GEN-LAST:event_mnuCadastroAActionPerformed

    private void mnuCadastroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroBActionPerformed
        // Recupera uma instância visível e não-iconficada da janela
        InternaB internaB = InternaB.getInstance();

        // Se a janela ainda não foi adicionada à área de trabalho...
        if (!Arrays
                .asList(dskPrincipal.getAllFrames())
                .contains(internaB)) {
            dskPrincipal.add(internaB);
        }

        tornarVisivel(internaB);

    }//GEN-LAST:event_mnuCadastroBActionPerformed

    private void mnuCadastroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroCActionPerformed
        // Recupera uma instância visível e não-iconficada da janela
        InternaC internaC = InternaC.getInstance();

        // Se a janela ainda não foi adicionada à área de trabalho...
        if (!Arrays
                .asList(dskPrincipal.getAllFrames())
                .contains(internaC)) {
            dskPrincipal.add(internaC);
        }

        tornarVisivel(internaC);
    }//GEN-LAST:event_mnuCadastroCActionPerformed

    /**
     * Reuso de funcionalidade de exibição de janela interna.
     * 
     * @param janela Janela interna a ser ajustada
     */
    private void tornarVisivel(JInternalFrame janela) {
        // Verificação de janela válida
        if (janela == null) {
            return;
        }

        // Torna a janela visível
        janela.setVisible(true);

        try {
            // Restaura a janela caso esteja minimizada
            janela.setIcon(false);

            // Leva o foco para a janela
            janela.setSelected(true);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Traz a janela para o primeiro plano
        janela.toFront();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCadastroA;
    private javax.swing.JMenuItem mnuCadastroB;
    private javax.swing.JMenuItem mnuCadastroC;
    private javax.swing.JMenuBar mnuPrincipal;
    // End of variables declaration//GEN-END:variables
}
